language: node_js
node_js:
- node
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: Egl89ZzwqbxoRX7mE9v3W273gfL/VerFfOYMK3JP+2ujcrgsTccezEEXMYlpTeOhj6B7UNLfjFIXVZfYWEOf8ibDoyEJgb9xmgV+1D0HKz00mnwl7HOrBgEfI1nbhzBieqD3RGB2xrRKj5R0rX3byD2RTRW+n6nnOiuo2LlIHhMNI5qCdd0ZWyJrEBG8s6Vfocy/cTMBzlE7/bG7ZgThF4q6Uk0rWTxpQ0HRlDiervE/flczrWyGLVBVUppxpyW4tv9ElLlVyUzCg3FHj56mtWpi1P3NWKGJwHMYwx1OwuTYbd583IzTwYSnWodrOLA3ljqnOXtCLl6gDJ9kMjNyo8oWuhxHxjjfw+b/O90eThzvAnwIN+zIShO/BK8eGqO/vaL6I+mYu/5bsoEt6KR9Q8dzbVUIpaadvNSVUFdJ3eowtJSfM+r0WwaPQ/3C6wWT6Rvu+60dvhUrGqckXsqo2J0fGcyrusrA0kurypkpdYPlCbly6pdAgy0UDWF4rF0I+FeTp/gVAX6IQ4m3zBNuGDBo2NsW93CkheqVFPua/shNCxa1DU97e5zRB4QJGzm2vSttSGhAlzuRzMZDlzkpb4aspZH6yEz/NsOX6x1uNFvjrSH4YsuOov+ch7/sw7VXVRaypork7tB0C6JGUR8yJVOMWQNBqfl2nCQzeNbYAvA=
  app: conway-gretz
  skip_cleanup: true
  on:
    repo: jgretz/conwaysgameoflife
