language: node_js
node_js:
- node
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: bB7db0sONfVQBTUIlVLIgRoiHc0t+uu5l4sLv381QlPYfUUvM1bYttVPn054PMrx/hGYkVMgqVjaG8wPa/2TwTMmTmadyt14YIRyq6F861DiNxnV1h3irPKv+3H/BcBYk+OFAYhm49+L5GRVIUuwX1ER6ycQIv7sc7Wmr3ZtwYFG29NrQeytgnc23V/Bhns7qn4SlAIQlzzdMrvqumenYj8CoTWlMhyvOUWzfmC+co/lTDu4rIeT37yHbaIR14jGnuGf0PTHcBH4RFu5VGqJ5H2QNV9aFKHZGpG92hLbEq2V7Xoz3D0u3dFoG23yu9y7wL1kJzi7AtHD5tkxFHXCRczkZRGns87ns4npObWRJMXR+GOCn5fN74S6WRoo1/I/09gAEQyAJtXPg53cTQd5bbsn3kJzvd23SzjlmAJa7uqmWbxorW31s+R6Ip7wJjQC75TgqAP1dy6xSpZWH/B13Hzc8vazyBj1YS7HEp9bYDLSF8s1NLgB52V2/skATmKRv84or4xJLKHed/Vtyy5rhosxaHTWdYs7icMMxygGbQQVjEUf1AoP0/1Mbh7QeBXXlFZje01YevqE7QsjZr36JNrLvrTUmJIIFQRXscriUuAFMtIX2DiG+1dv92ZCoPZREoN5oEPOd4sZYevkHpq/ZFWLru1XowcsE12HnoKMfZI=
  app: conway-gretz
  skip_cleanup: true
  on:
    repo: jgretz/conwaysgameoflife
